### ISSUE TITLE
App Crash after adding action

### ISSUE THREAD

**Issue by mhoellner** [elen-niedermeyer/NFC-Trigger#14]
The application crashes after adding an action to the action list and pushing the home button. Crashes only on Android 7.1.1 right now.
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.niedermeyer.nfc_trigger, PID: 26833
    java.lang.RuntimeException: Parcel: unable to marshal value Alarm: 00:00
        at android.os.Parcel.writeValue(Parcel.java:1477)
        at android.os.Parcel.writeList(Parcel.java:812)
        at android.os.Parcel.writeValue(Parcel.java:1424)
        at android.os.Parcel.writeArrayMapInternal(Parcel.java:724)
        at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1408)
        at android.os.Bundle.writeToParcel(Bundle.java:1157)
        at android.os.Parcel.writeBundle(Parcel.java:764)
        at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3713)
        at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3797)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6165)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

Can probably be resolved by making the `Action.kt` a `Parcelable`. This way, the `onSaveInstanceState` method in `NewTriggerActivity.kt` can maybe save it correctly.

**Comment by mhoellner** [comment]
We can't implement the whole Parcelable interface in the Action.kt as it is abstract and we need a constructor for it to work. I implemented part of the interface in the base class and the other part in the AlarmAction.kt

Is currently blocked by #7 as it changes a lot of code around.

**Comment by elen-niedermeyer** [comment]
merged
